language: php

php:
  - "7.3"
  - "7.2"
  - "7.1"

install: composer install --no-interaction

cache:
  directories:
    - "$HOME/.composer/cache"

services:
  - mysql

before_install:
  - mysql -e 'create database if not exists dataflow;'
  - cp -f tests/functional/config/db-config.travis.php tests/functional/config/db-config.php

script:
  - vendor/bin/phpunit --coverage-clover ./coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover ./coverage.clover

notifications:
  email: true

matrix:
  fast_finish: true
